import time
import logging
import yaml
import os
import re
import subprocess
from datetime import timedelta
from datetime import datetime
import threading
import shutil
import convert_cocotb_testbench
import convert_cocotb_makefile
import batch_file_operation

# Constants
COCOTB_LOG_FILE = "cocotb_sim.log"
COCOTB_RESULT_FILE = "results.xml"
SPACE_LIMIT = 80  # Maximum space tuned for the screen width
COCOTB_EXEC = "make"


# Class of a Cocotb job run manager
class CocotbJobManager:
    def __init__(self):
        # Internal data
        self.__new_thread_wait_time_ = 1  # [sec.] Give a wait time before starting the next thread. Avoid any conflicts in switching directories
        self.__sim_start_wait_time_ = 1  # [sec.] Give a wait time between cleaning up previous results and starting a simulation. Avoid any conflicts in switching directories
        self.__log_check_wait_time_ = 1  # [sec.] Give a wait time between cleaning up previous results and starting a simulation. Avoid any conflicts in switching directories
        self.__job_names_ = []
        self.__job_scripts_ = []
        self.__job_files_ = []
        self.__simulators_ = []
        self.__netlist_types_ = []
        self.__dump_waveforms_ = []
        self.__extra_params_ = []
        self.__rundirs_ = (
            []
        )  # Directory when Cocotb is actually called. All the intermediate files will be kept there
        self.__clean_previous_runs_ = []
        self.__error_counts_ = []  # Flag it Cocotb run is successfully or not
        # Constants
        self.__DEFAULT_SIMULATOR_ = "vcs"
        self.__DEFAULT_NETLIST_TYPE_ = "rtl"
        self.__WAVE_FSDB_ = "fsdb"
        self.__WAVE_VCD_ = "vcd"
        self.__DISABLE_WAVE_ = "none"
        self.__DEFAULT_DUMP_WAVE_ = self.__DISABLE_WAVE_
        self.__COMMON_CLEAN_DIRS_ = [
            "__pycache__",
        ]
        self.__COMMON_CLEAN_FILES_ = [
            "results.xml",
            "*.log",
            "*.fsdb",
            "*.vcd",
        ]
        self.__CLEAN_FILES_ = {}
        ## Output files generated by VCS during simulation
        self.__CLEAN_FILES_["icarus"] = [
            "*.out",
        ]
        self.__CLEAN_FILES_["modelsim"] = [
            "*.log",
            "*.vstf",
            "transcript",
        ]
        self.__CLEAN_FILES_["vcs"] = [
            "simv",
            "pli.tab",
            "verdi_config_file",
        ]
        self.__CLEAN_DIRS_ = {}
        ## Output files generated by VCS during simulation
        self.__CLEAN_DIRS_["icarus"] = [
            "sim_build",
        ]
        self.__CLEAN_DIRS_["vcs"] = [
            "csrc",
            "simv.daidir",
        ]
        self.__CLEAN_DIRS_["modelsim"] = [
            "work",
        ]

        self.__FILE_TYPE_COCOTB_MAKEFILE_ = "cocotb_makefile"
        self.__FILE_TYPE_COCOTB_TESTBENCH_ = "cocotb_testbench"

        self.__sdf_annotation_enabled_ = []
        self.__sdf_file_paths_ = []

    # Set the runtime directory to execute PTPX job
    def set_new_thread_wait_time(self, val):
        self.__new_thread_wait_time_ = val

    def set_sim_start_wait_time(self, val):
        self.__sim_start_wait_time_ = val

    def set_log_check_wait_time(self, val):
        self.__log_check_wait_time_ = val

    # Create a new job
    def create_job(self, job_name):
        if job_name in self.__job_names_:
            raise Exception(
                "Duplicated job names: another job has already been created under the same name!"
            )
        self.__job_names_.append(job_name)
        # Give a default empty script
        self.__job_files_.append({})
        # Set a default value
        self.__job_scripts_.append("")
        self.__rundirs_.append("")
        self.__simulators_.append(self.__DEFAULT_SIMULATOR_)
        self.__netlist_types_.append(self.__DEFAULT_NETLIST_TYPE_)
        self.__dump_waveforms_.append(self.__DEFAULT_DUMP_WAVE_)
        self.__extra_params_.append("")
        self.__clean_previous_runs_.append(False)
        # Clear error count
        self.__error_counts_.append(0)
        # Add annotation enabled
        self.__sdf_annotation_enabled_.append(False)
        self.__sdf_file_paths_.append("")

    # Get the runtime directory for a given job
    def cocotb_rundir(self, job_name):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        return self.__rundirs_[job_idx]

    # Set the tcl script to run the PTPX job
    def add_file_to_job(self, job_name, fsrc, fdes, ftype):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__job_files_[job_idx][fsrc] = [fdes, ftype]
        if ftype == self.__FILE_TYPE_COCOTB_MAKEFILE_:
            self.set_runtime_dir(job_name, os.path.dirname(os.path.abspath(fdes)))
            # Set the script to run when calling this job
            self.__job_scripts_[job_idx] = os.path.abspath(fdes)

    # Set the runtime directory to execute PTPX job
    def set_runtime_dir(self, job_name, val):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__rundirs_[job_idx] = val

    # Set the runtime directory to execute PTPX job
    def set_simulator(self, job_name, val):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__simulators_[job_idx] = val

    # Set the runtime directory to execute PTPX job
    def set_netlist_type(self, job_name, val):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__netlist_types_[job_idx] = val

    # Set the runtime directory to execute PTPX job
    def set_extra_parameters(self, job_name, val):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__extra_params_[job_idx] = val

    # Set the runtime directory to execute PTPX job
    def set_clean_previous_run(self, job_name, val):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__clean_previous_runs_[job_idx] = val

    # Set the runtime directory to execute PTPX job
    def set_waveform_format(self, job_name, val):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__dump_waveforms_[job_idx] = val

    # Add sdf annotation for a given job
    def set_sdf_annotation_enabled(self, job_name, val):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__sdf_annotation_enabled_[job_idx] = val

    def set_sdf_file_path(self, job_name, val):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        self.__sdf_file_paths_[job_idx] = val

    # Run a Cocotb job with a given job name
    def __thread_run_cocotb(self, thread_sema, job_name, check_log, job_status, job_time, curr_dir):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)

        with thread_sema:
            thread_name = threading.currentThread().getName()

            # Log runtime
            start_time = time.time()

            start_time_str = datetime.fromtimestamp(start_time).isoformat()
            time_logging_space = (
                "." * (SPACE_LIMIT - len(job_name) - len(" start at") - len(start_time_str) - 2)
                + " "
            )
            logging.info(job_name + " start at" + time_logging_space + start_time_str)

            job_status[job_name] = 0

            # Check if the tcl script is valid
            if not os.path.isfile(self.__job_scripts_[job_idx]):
                raise Exception(
                    f"Cocotb Makefile '{self.__job_scripts_[job_idx]}' is not a valid file"
                )
            # TODO: Clean up previous run?
            for fclean in self.__COMMON_CLEAN_FILES_:
                curr_fpath = os.path.join(curr_dir, self.__rundirs_[job_idx], fclean)
                if os.path.exists(curr_fpath):
                    logging.info(f"Removed {fclean} for job '{job_name}")
                    os.remove(curr_fpath)
            for fclean in self.__COMMON_CLEAN_DIRS_:
                curr_fpath = os.path.join(curr_dir, self.__rundirs_[job_idx], fclean)
                if os.path.exists(curr_fpath) and os.path.isdir(curr_fpath):
                    logging.info(f"Removed {fclean} for job '{job_name}")
                    shutil.rmtree(curr_fpath, ignore_errors=True)
            if self.__clean_previous_runs_[job_idx]:
                logging.info("Clean up previous run before simulation")
                if self.__simulators_[job_idx] in self.__CLEAN_FILES_:
                    for fclean in self.__CLEAN_FILES_[self.__simulators_[job_idx]]:
                        curr_fpath = os.path.join(curr_dir, self.__rundirs_[job_idx], fclean)
                        if os.path.exists(curr_fpath):
                            logging.info(f"Removed {fclean} for {job_name}")
                            os.remove(curr_fpath)
                if self.__simulators_[job_idx] in self.__CLEAN_DIRS_:
                    for fclean in self.__CLEAN_DIRS_[self.__simulators_[job_idx]]:
                        curr_fpath = os.path.join(curr_dir, self.__rundirs_[job_idx], fclean)
                        if os.path.exists(curr_fpath) and os.path.isdir(curr_fpath):
                            logging.info(f"Removed {fclean} for {job_name}")
                            shutil.rmtree(curr_fpath, ignore_errors=True)
            time.sleep(self.__sim_start_wait_time_)
            # Change to the runtime directory
            os.chdir(os.path.join(curr_dir, self.__rundirs_[job_idx]))
            logging.info(f"Changed to directory: {self.__rundirs_[job_idx]}")
            # Run Cocotb
            run_cmd = (
                COCOTB_EXEC
                + " "
                + " SIM="
                + self.__simulators_[job_idx]
                + " NETLIST_TYPE="
                + self.__netlist_types_[job_idx]
            )
            if self.__dump_waveforms_[job_idx] == self.__WAVE_FSDB_:
                run_cmd += " DUMP_FSDB=1"
            elif self.__dump_waveforms_[job_idx] == self.__WAVE_VCD_:
                run_cmd += " DUMP_VCD=1"
            elif self.__dump_waveforms_[job_idx] != self.__DISABLE_WAVE_:
                job_status[job_name] += 1
                raise Exception(
                    f"Unknown waveform file format '{self.__dump_waveforms_[job_idx]}'! Expect [none|vcd|fsdb]"
                )
            # Add SDF annotation if enabled
            if self.__sdf_annotation_enabled_[job_idx] and self.__sdf_file_paths_[job_idx]:
                run_cmd += " SDF_FILE=" + self.__sdf_file_paths_[job_idx]
            # Add other parameters
            for sim_arg in self.__extra_params_[job_idx].split(","):
                if sim_arg:
                    if len(sim_arg.split(":")) != 2:
                        job_status[job_name] += 1
                        raise Exception(
                            f"Invalid parameter format {sim_arg}! Expect <arg_name>:<arg_value>"
                        )
                    run_cmd += " " + sim_arg.split(":")[0] + "=" + sim_arg.split(":")[1]

            # Current, we have to disable checks because PrimeTime has issues when loading library compilers
            log_fname = os.path.join(
                os.path.join(curr_dir, self.__rundirs_[job_idx]), COCOTB_LOG_FILE
            )
            with open(log_fname, "w") as log_f:
                logging.info(
                    f"Running the following command for job '{job_name}':\n\t{run_cmd}\nMay use for debugging"
                )
                logging.info(f"For job '{job_name}': Redirect output to {log_fname}")
                make_process = subprocess.Popen(run_cmd, shell=True, stdout=log_f, stderr=log_f)
                if (make_process.wait()) != 0:
                    job_status[job_name] += 1
            # Restore
            os.chdir(curr_dir)

            end_time = time.time()
            job_time[job_name] = timedelta(seconds=(end_time - start_time))

            time_str = "Running Cocotb job '" + job_name + "' took " + str(job_time[job_name])
            end_time_str = datetime.fromtimestamp(end_time).isoformat()
            logging.info(job_name + " ends at" + time_logging_space + end_time_str)

            # check log
            if check_log:
                # Wait until log file is stablized. In some server, disk operation is slow
                time.sleep(self.__log_check_wait_time_)
                job_status[job_name] += self.parse_cocotb_log(job_name)

            return job_status

    # Check a cocotb log, count the number errors found
    def parse_cocotb_log(self, job_name):
        num_errors = 0
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)
        # Log runtime
        start_time = time.time()
        log_path = os.path.join(self.__rundirs_[job_idx], COCOTB_RESULT_FILE)
        log_abspath = os.path.abspath(log_path)
        # Check if the tcl script is valid
        if not os.path.isfile(log_abspath):
            raise Exception(f"Expect Cocotb run log file at '{log_abspath}' but not found!")
        logging.info(f"Checking Cocotb log file '{log_abspath}'...")

        with open(log_abspath, "r") as logf:
            log_lines = logf.readlines()
            for line_num, curr_line in enumerate(log_lines):
                is_err = False
                if re.search("failure", curr_line):
                    is_err = True
                if is_err:
                    logging.error(curr_line)
                    num_errors += 1

        end_time = time.time()
        time_diff = timedelta(seconds=(end_time - start_time))

        time_str = "Checking Cocotb log file took " + str(time_diff)
        logging.info(time_str)

        return num_errors

    # Run all Cocotb jobs with a given maximum number of jobs in parrallel
    def run_cocotb_all(self, max_num_jobs, check_log):
        # Create thread pool
        thread_sema = threading.BoundedSemaphore(value=max_num_jobs)
        thread_list = []

        # Job status dashboard
        job_status = {}
        job_time = {}

        curr_dir = os.getcwd()

        for key in self.__job_names_:
            curr_thread = threading.Thread(
                target=self.__thread_run_cocotb,
                args=(thread_sema, key, check_log, job_status, job_time, curr_dir),
            )
            curr_thread.start()
            thread_list.append(curr_thread)
            time.sleep(self.__new_thread_wait_time_)

        for curr_thread in thread_list:
            curr_thread.join()

        # check log
        for key in self.__job_names_:
            job_status[key] += self.parse_cocotb_log(key)

        for key in self.__job_names_:
            job_idx = self.__job_names_.index(key)
            curr_job_status = job_status[key]
            # Create a space when logging
            logging_space = " " + "." * (SPACE_LIMIT - len(key) - 2) + " "
            self.__error_counts_[job_idx] += curr_job_status
            if curr_job_status == 0:
                logging.info(key + logging_space + "[Pass]")
            else:
                logging.info(key + logging_space + "[Fail]")
            # Show runtime
            time_diff = job_time[key]
            time_str = "took " + str(time_diff)
            time_logging_space = "." * (SPACE_LIMIT - len(key) - len(time_str) - 2) + " "
            logging.info(key + time_logging_space + time_str)

    # Run a Cocotb job with a given job name
    def __thread_setup_cocotb(
        self, thread_sema, job_name, check_log, job_status, job_time, curr_dir
    ):
        if job_name not in self.__job_names_:
            raise Exception("Intend to access/mutate a job which has not been created!")
        job_idx = self.__job_names_.index(job_name)

        with thread_sema:
            thread_name = threading.currentThread().getName()

            # Log runtime
            start_time = time.time()

            start_time_str = datetime.fromtimestamp(start_time).isoformat()
            time_logging_space = (
                "." * (SPACE_LIMIT - len(job_name) - len(" start at") - len(start_time_str) - 2)
                + " "
            )
            logging.info(job_name + " start at" + time_logging_space + start_time_str)

            job_status[job_name] = 0

            # Setup files for symbolic links
            for fsrc in self.__job_files_[job_idx].keys():
                fdes = self.__job_files_[job_idx][fsrc][0]
                ftype = self.__job_files_[job_idx][fsrc][1]
                # Based on file type, use different operations
                if (
                    ftype != self.__FILE_TYPE_COCOTB_MAKEFILE_
                    and ftype != self.__FILE_TYPE_COCOTB_TESTBENCH_
                ):
                    if ftype in ["gl_sdf", "pl_sdf"]:
                        batch_file_operation.generate_symbolic_link(fsrc, fdes)
                        # If SDF annotation is enabled, set the SDF file path based on netlist type
                        if self.__sdf_annotation_enabled_[job_idx]:
                            # Only set SDF file path if it matches the current netlist type
                            netlist_type = self.__netlist_types_[job_idx]
                            if (netlist_type in ["gl", "gate_level"] and ftype == "gl_sdf") or (
                                netlist_type in ["pl", "post_layout"] and ftype == "pl_sdf"
                            ):
                                self.set_sdf_file_path(job_name, fdes)
                    else:
                        batch_file_operation.generate_symbolic_link(fsrc, fdes)

            # Setup files for cocotb makefile
            for fsrc in self.__job_files_[job_idx].keys():
                fdes = self.__job_files_[job_idx][fsrc][0]
                ftype = self.__job_files_[job_idx][fsrc][1]
                # Copy and adapt the makefile
                if ftype == self.__FILE_TYPE_COCOTB_MAKEFILE_:
                    # Check if source file exists before copying
                    if os.path.exists(fsrc):
                        batch_file_operation.generate_copy(fsrc, fdes)
                        convert_cocotb_makefile.convert_makefile(fdes, "_top_formal_verification")
                    else:
                        logging.warning(f"Makefile source file does not exist: {fsrc}")

            # Setup files for cocotb testbench
            for fsrc in self.__job_files_[job_idx].keys():
                fdes = self.__job_files_[job_idx][fsrc][0]
                ftype = self.__job_files_[job_idx][fsrc][1]
                # Copy and adapt the testbench
                if ftype == self.__FILE_TYPE_COCOTB_TESTBENCH_:
                    # Check if source file exists before copying
                    if os.path.exists(fsrc):
                        batch_file_operation.generate_copy(fsrc, fdes)
                        convert_cocotb_testbench.convert_cocotb_testbench(
                            fsrc,
                            fdes,
                            "fabric_bitstream.xml",
                            "fabric_bitstream_base.xml",
                            "cocotb_force_bitstream",
                        )
                    else:
                        logging.warning(f"Testbench source file does not exist: {fsrc}")

            end_time = time.time()
            job_time[job_name] = timedelta(seconds=(end_time - start_time))

            time_str = "Running Cocotb job '" + job_name + "' took " + str(job_time[job_name])
            end_time_str = datetime.fromtimestamp(end_time).isoformat()
            logging.info(job_name + " ends at" + time_logging_space + end_time_str)

            # check files
            for fsrc in self.__job_files_[job_idx].keys():
                fdes = self.__job_files_[job_idx][fsrc][0]
                if (
                    not os.path.isfile(fdes)
                    and not os.path.isdir(fdes)
                    and not os.path.islink(fdes)
                ):
                    logging.error(f"File {fdes} is not properly linked/copied to the destination!")
                    job_status[job_name] += 1

            return job_status

    # Setup all Cocotb jobs with a given maximum number of jobs in parrallel
    def run_setup_all(self, max_num_jobs, check_log):
        # Create thread pool
        thread_sema = threading.BoundedSemaphore(value=max_num_jobs)
        thread_list = []

        # Job status dashboard
        job_status = {}
        job_time = {}

        curr_dir = os.getcwd()

        for key in self.__job_names_:
            curr_thread = threading.Thread(
                target=self.__thread_setup_cocotb,
                args=(thread_sema, key, check_log, job_status, job_time, curr_dir),
            )
            curr_thread.start()
            thread_list.append(curr_thread)
            time.sleep(self.__new_thread_wait_time_)

        for curr_thread in thread_list:
            curr_thread.join()

        for key in self.__job_names_:
            job_idx = self.__job_names_.index(key)
            curr_job_status = job_status[key]
            # Create a space when logging
            logging_space = " " + "." * (SPACE_LIMIT - len(key) - 2) + " "
            self.__error_counts_[job_idx] += curr_job_status
            if curr_job_status == 0:
                logging.info(key + logging_space + "[Pass]")
            else:
                logging.info(key + logging_space + "[Fail]")
            # Show runtime
            time_diff = job_time[key]
            time_str = "took " + str(time_diff)
            time_logging_space = "." * (SPACE_LIMIT - len(key) - len(time_str) - 2) + " "
            logging.info(key + time_logging_space + time_str)

    # Check if run is successful
    def num_errors(self):
        return sum(self.__error_counts_)

    # Clear all the data
    def clear(self):
        self.__init__()
